site_name: Terminal for MkDocs
site_url: https://ntno.github.io/mkdocs-terminal
repo_url: https://github.com/ntno/mkdocs-terminal
edit_uri_template: https://github.com/ntno/mkdocs-terminal/edit/main/documentation/docs/{path}
copyright: Copyright 2023 Natan Organick, All rights reserved
site_author: ntno

nav:
    - Home: 'index.md'
    - Configuration:
      - Index: 'configuration/index.md'
      - Color Palettes: 
        - Index: 'configuration/palettes/index.md'
        - Default: 'configuration/palettes/default.md'
        - Gruvbox Dark: 'configuration/palettes/gruvbox-dark.md'
        - Dark: 'configuration/palettes/dark.md'
        - Pink: 'configuration/palettes/pink.md'
        - Sans: 'configuration/palettes/sans.md'
        - Sans Dark: 'configuration/palettes/sans-dark.md'
      - Code Highlighting:
        - Index: 'configuration/code-highlighting/index.md'
        - '___Highlight.js': 'configuration/code-highlighting/highlightjs.md'
      - Features: 'configuration/features.md'
      - Plugins: 'configuration/plugins/index.md'
      - '___Git Revision': 'configuration/plugins/git-revision.md'
      - '___Macros': 'configuration/plugins/macros.md'
      - '___Search': 'configuration/plugins/search.md'      
      - Extensions: 'configuration/extensions/index.md'
      - '___Markdown': 'configuration/extensions/python-markdown.md'
      - '___PyMdown': 'configuration/extensions/pymdown-extensions.md'
      - '___Snippets': 'configuration/extensions/snippets.md'
      - Overrides: 'configuration/overrides/index.md'
      - '___Blocks': 'configuration/blocks.md'    
    - Navigation:
        - Section Indexes: 'navigation/section-indexes.md'
        - Table of Contents: 'navigation/toc.md'
    - Tile Grid:
      - Index: 'tile-grid/index.md'
      - Tile Reference: 'tile-grid/tile.md'
      - Grid Reference: 'tile-grid/grid.md'
      - Pluglet Reference: 'tile-grid/pluglet.md'
      - Example: 'tile-grid/examples/example-page.md'
      - Image Only: 'tile-grid/examples/images-only.md'
      - Link Only: 'tile-grid/examples/links-only.md'
      - Override Styling: 'tile-grid/examples/override-styling.md'
      - Inline Example: 'tile-grid/examples/inline.md'
    - Elements:
      - Blockquotes: 'elements/blockquotes.md'
      - Buttons: 'elements/buttons.md'
      - Code: 'elements/code.md'
      - Code, Highlighted: 'elements/code_hilighting.md'
      - Definitions: 'elements/definitions.md'
      - Figures: 'elements/figure.md'
      - Footnotes: 'elements/footnotes.md'
      - Links: 'elements/links.md'
      - Lists: 'elements/lists.md'
      - Tables: 'elements/table.md'
      - Tooltips: 'elements/tooltips.md'
      - Typography: 'elements/typography.md'
    - Install: 'install.md'
    - Releases: 'releases.md'

markdown_extensions:
  # Python Markdown  
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - toc:
      permalink: "#"
      permalink_title: Anchor link to this section for reference

  # PyMdown Extensions
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets:
      base_path: 
        - docs
  - pymdownx.highlight:
      use_pygments: false

plugins:
  - md-to-html
  - git-revision-date
  - search
  - exclude-search:      
      exclude:
        - overrides
        - about/coverage-report/*
        - configuration/palettes/*
        - elements/examples/*
      ignore:
        - configuration/palettes/index.md#theme-color-palettes
        - configuration/palettes/dark.md#dark-palette
        - configuration/palettes/default.md#default-palette
        - configuration/palettes/gruvbox-dark.md#gruvbox-dark-palette
        - configuration/palettes/pink.md#pink-palette
        - configuration/palettes/sans-dark.md#sans-dark-palette
        - configuration/palettes/sans.md#sans-palette
  - macros:
      modules: 
        - mkdocs-terminal:terminal.pluglets.tile_grid.main

## deploy settings
theme:
  name: terminal
  custom_dir: theme_overrides
  features:
    - footer.prev_next
    - navigation.side.indexes
    - revision.date
    - revision.history
  static_templates:
    - 404.html
    - about/coverage-report/index.html

extra_css:
  - overrides/extra.css
              