site_name: MkDocs Terminal
site_url: https://ntno.github.io/mkdocs-terminal
repo_url: https://github.com/ntno/mkdocs-terminal
copyright: Copyright 2023 Natan Organick, All rights reserved
site_author: ntno

nav:
    - Home: 'index.md'
    - Configuration:
      - Index: 'configuration/index.md'
      - Color Palettes: 
        - Index: 'configuration/palettes/index.md'
        - Default: 'configuration/palettes/default.md'
        - Dark: 'configuration/palettes/dark.md'
        - Pink: 'configuration/palettes/pink.md'
        - Sans: 'configuration/palettes/sans.md'
        - Sans Dark: 'configuration/palettes/sans_dark.md'
      - Features: 'configuration/features.md'
    - Navigation:
        - Section Indexes: 'navigation/section-indexes.md'
        - Table of Contents: 'navigation/toc.md'
    - Install: 'install.md'

markdown_extensions:
  - meta
  - attr_list
  - toc:
      permalink: "#"

theme:
  name: terminal
  features:
    - navigation.side.indexes
