site_name: MkDocs Terminal
site_url: https://ntno.github.io/mkdocs-terminal
repo_url: https://github.com/ntno/mkdocs-terminal
copyright: Copyright 2023 Natan Organick, All rights reserved
site_author: ntno

nav:
    - Home: 'index.md'
    - Configuration:
      - Index: 'configuration/index.md'
      - Color Palettes: 
        - Index: 'configuration/palettes/index.md'
        - Default: 'configuration/palettes/default.md'
        - Gruvbox Dark: 'configuration/palettes/gruvbox_dark.md'
        - Dark: 'configuration/palettes/dark.md'
        - Pink: 'configuration/palettes/pink.md'
        - Sans: 'configuration/palettes/sans.md'
        - Sans Dark: 'configuration/palettes/sans_dark.md'
      - Features: 'configuration/features.md'
      - Extensions: 
        - Index: 'configuration/extensions/index.md'
        - Python Markdown: 'configuration/extensions/python-markdown.md'
        - Python Markdown Extensions: 'configuration/extensions/python-markdown-extensions.md'
    - Navigation:
        - Section Indexes: 'navigation/section-indexes.md'
        - Table of Contents: 'navigation/toc.md'
    - Install: 'install.md'

markdown_extensions:
  # Python Markdown  
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - toc:
      permalink: "#"


  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:materialx.emoji.twemoji
  #     emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


theme:
  name: terminal
  features:
    - navigation.side.indexes
