site_name: MkDocs Terminal
site_url: https://ntno.github.io/mkdocs-terminal
repo_url: https://github.com/ntno/mkdocs-terminal
copyright: Copyright 2023 Natan Organick, All rights reserved
site_author: ntno

nav:
    - Home: 'index.md'
    - Configuration:
      - Index: 'configuration/index.md'
      - Color Palettes: 
        - Index: 'configuration/palettes/index.md'
        - Default: 'configuration/palettes/default.md'
        - Gruvbox Dark: 'configuration/palettes/gruvbox_dark.md'
        - Dark: 'configuration/palettes/dark.md'
        - Pink: 'configuration/palettes/pink.md'
        - Sans: 'configuration/palettes/sans.md'
        - Sans Dark: 'configuration/palettes/sans_dark.md'
      - Features: 'configuration/features.md'
      - Extensions: 'configuration/extensions/index.md'
      - Python Markdown: 'configuration/extensions/python-markdown.md'
      - PyMdown Extensions: 'configuration/extensions/py-mdown-extensions.md'
    - Navigation:
        - Section Indexes: 'navigation/section-indexes.md'
        - Table of Contents: 'navigation/toc.md'
    - Elements:
      - Blockquotes: 'elements/blockquotes.md'
      - Buttons: 'elements/buttons.md'
      - Definitions: 'elements/definitions.md'
      - Figures: 'elements/figure.md'
      - Footnotes: 'elements/footnotes.md'
      - Links: 'elements/links.md'
      - Tables: 'elements/table.md'
      - Tooltips: 'elements/tooltips.md'
      - Typography: 'elements/typography.md'
    - Install: 'install.md'

markdown_extensions:
  # Python Markdown  
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - tables
  - toc:
      permalink: "#"
      permalink_title: Anchor link to this section for reference


  # PyMdown Extensions
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets:
      base_path: 
        - docs

## deploy settings
theme:
  name: terminal
  features:
    - navigation.side.indexes